### ISSUE TITLE
gb2312估计应该用 simplifiedchinese.HZGB2312

### ISSUE THREAD

**Issue by missdeer** [sundy-li/html2article#11]
https://github.com/sundy-li/html2article/blob/f7d95a6f91d8a6e642e194ef1ccaded4f8b1fe41/chadef.go#L42

另外，[这篇文章](https://blog.minidump.info/2016/10/golang-convert-between-cjk-encodings-and-utf8/)讲了怎么用pure go做CJK和UTF-8之间的转换

**Comment by sundy-li** [comment]
#10   这个mr 不知道能不能解决这个问题

**Comment by missdeer** [comment]
@sundy-li 那个PR用了qiniu/iconv，引入了cgo，增加了编译依赖，特别是交叉编译就不好搞了，不大好

**Comment by orca-zhang** [comment]
@missdeer  确实有这些问题，之前在一个简单原型中使用了大佬的库，发现了抓取一些页面的编码问题，本来是在Windows下测试的，但是因为引入iconv，不得不在linux下编译，交叉编译好像不可行，因为windows的libiconv很难找，最早是打算手动转码来着。你发的那个解决方案看起来不错哇，可行的话，可以考虑替换掉iconv，不过还有个问题是有的页面需要进行编码检测，我 暂时用了enca。

**Comment by sundy-li** [comment]
七牛那个包之前在使用过程中有一些bug，虽然后面修复了，但还是倾向手写chardef，我试试看能不能你们建议的其他方案来解决编码问题

**Comment by sundy-li** [comment]
我发现官方已经实现了这个,  see [here](https://github.com/golang/net/blob/master/html/charset/charset.go)

**Comment by sundy-li** [comment]
最近提交用的是这个方法

**Comment by missdeer** [comment]
这个赞，代码精简好多！

**Comment by sundy-li** [comment]
没有很多不同编码的网页来测试, 有问题再沟通!

**Comment by orca-zhang** [comment]
666~
